name: "03 â€“ Workflow Runners"

on: workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: tf-uczen-wieslaw-glod-gha-gh
    steps:
      - name: Show OS
        run: |
          echo "This job is running on an Ubuntu runner."
          echo "$RUNNER_OS"

  